# Generated by Django 3.1.5 on 2021-01-08 05:11

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mr & Mrs', help_text='Easy way to reference party', max_length=64, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Primary Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('guests_allowed', models.IntegerField(default=1, verbose_name='Max Guests Allowed')),
                ('tier', models.IntegerField(choices=[(0, 'Wedding Party'), (1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Fallback')], verbose_name='Priority Tier')),
                ('association', models.CharField(choices=[('family', 'Family'), ('friend', 'Friends'), ('work', 'Work Colleague'), ('fam_friend', 'Family Friend')], max_length=16, verbose_name='Association')),
                ('side', models.CharField(choices=[('bridge', 'Bridget'), ('dan', 'Dan')], max_length=8, verbose_name='Wedding Side')),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.party')),
            ],
        ),
    ]
