# Generated by Django 3.1.5 on 2021-01-10 20:40

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import wedding.guests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mr & Mrs', help_text='Easy way to reference party', max_length=64, verbose_name='Name')),
                ('email', models.EmailField(blank=True, help_text='Email to contact main party individual, if available.', max_length=254, null=True, verbose_name='Primary Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number to contact main party individual, if available.', max_length=128, null=True, region=None)),
                ('contact_method', models.CharField(choices=[('emailEmail', 'Email'), ('phone', 'Phone (Texting)'), ('mail', 'Postal Mail')], default='mail', max_length=16, verbose_name='Preferred Contact Method')),
                ('tier', models.IntegerField(choices=[(0, 'Wedding Party'), (1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Fallback')], verbose_name='Priority Tier')),
                ('association', models.CharField(choices=[('family', 'Family'), ('friend', 'Friends'), ('work', 'Work Colleague'), ('fam_friend', 'Family Friend')], max_length=16, verbose_name='Association')),
                ('side', models.CharField(choices=[('bridge', 'Bridget'), ('dan', 'Dan')], max_length=8, verbose_name='Wedding Side')),
                ('is_invited', models.BooleanField(default=False, help_text='Whether or not the party is actually invited.')),
                ('guests_allowed', models.IntegerField(default=2, help_text='How many people should we expect', verbose_name='Max Guests Allowed')),
                ('rehearsal_dinner', models.BooleanField(default=False, help_text='Whether the party is invited to the rehearsal dinner')),
                ('is_attending', models.BooleanField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('address', address.models.AddressField(blank=True, help_text='Address of the main party individual, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('role', models.CharField(blank=True, choices=[('best_man', 'Best Man'), ('maid_of_honor', 'Maid of Honor'), ('groomsman', 'Groomsman'), ('bridesmaid', 'Bridesmaid')], max_length=16, null=True, verbose_name='Wedding Role')),
                ('is_child', models.BooleanField(default=False)),
                ('picture', models.ImageField(null=True, upload_to=wedding.guests.models.guest_picture_path)),
                ('details', models.TextField(blank=True, default='')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='guests.party')),
            ],
            options={
                'ordering': ['party', 'last_name'],
                'default_related_name': 'guests',
            },
        ),
    ]
