# Generated by Django 3.1.5 on 2021-01-08 05:27

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='contact_method',
            field=models.CharField(choices=[('emailEmail', 'Email'), ('phone', 'Phone (Texting)'), ('mail', 'Postal Mail')], default='mail', max_length=16, verbose_name='Preferred Contact Method'),
        ),
        migrations.AlterField(
            model_name='party',
            name='address',
            field=address.models.AddressField(blank=True, help_text='Address of the main party individual, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.EmailField(blank=True, help_text='Email to contact main party individual, if available.', max_length=254, null=True, verbose_name='Primary Email'),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number to contact main party individual, if available.', max_length=128, null=True, region=None),
        ),
    ]
