# Generated by Django 3.1.5 on 2021-01-17 00:12

from django.db import migrations, models
import phonenumber_field.modelfields
import wedding.guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Needed only if they are in the wedding party.'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Needs "+1" and then 10 digit, ie +17165554444', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=models.ImageField(blank=True, help_text='Needed if they are in the wedding party', null=True, upload_to=wedding.guests.models.guest_picture_path),
        ),
    ]
