# Generated by Django 3.1.5 on 2021-01-08 05:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20210108_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'default_related_name': 'guests', 'ordering': ['party', 'last_name']},
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='party',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='is_attending',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='is_invited',
            field=models.BooleanField(default=False, help_text='Whether or not the party is actually invited.'),
        ),
        migrations.AddField(
            model_name='party',
            name='rehearsal_dinner',
            field=models.BooleanField(default=False, help_text='Whether the party is invited to the rehearsal dinner'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='guests.party'),
        ),
        migrations.AlterField(
            model_name='party',
            name='guests_allowed',
            field=models.IntegerField(default=2, help_text='How many people should we expect', verbose_name='Max Guests Allowed'),
        ),
    ]
