# Generated by Django 3.1.5 on 2021-01-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20210117_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('& Guest', 'Individual with Guest'), ('Couple', 'Couple with Two Known Guests'), ('Family', 'Family with Kids')], default='& Guest', help_text='Defines the party type and will automatically suffix correctly', max_length=32, verbose_name='Party Type'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(default='', help_text='First & last of main party member', max_length=64, verbose_name='Name'),
        ),
    ]
