# Generated by Django 3.1.5 on 2021-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20210108_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='role',
            field=models.CharField(blank=True, choices=[('best_man', 'Best Man'), ('maid_of_honor', 'Maid of Honor'), ('groomsman', 'Groomsman'), ('bridesmaid', 'Bridesmaid')], max_length=16, null=True, verbose_name='Wedding Role'),
        ),
    ]
