# Generated by Django 3.1.5 on 2021-01-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_auto_20210117_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='party_contact',
            field=models.BooleanField(default=False, help_text='Use the same contact info as the party?', verbose_name='Party Contact'),
        ),
    ]
