# Generated by Django 3.1.5 on 2021-01-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_party_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='party_contact',
            field=models.BooleanField(default=False, help_text='Use the same contact info as the party? Leave the following blank.', verbose_name='Party Contact'),
        ),
    ]
