# Generated by Django 3.1.5 on 2021-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='guest',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Last Name'),
        ),
    ]
