# Generated by Django 3.1.5 on 2021-01-08 23:34

from django.db import migrations, models
import wedding.guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20210108_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=models.ImageField(null=True, upload_to=wedding.guests.models.guest_picture_path),
        ),
    ]
