# Generated by Django 3.1.5 on 2021-01-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_remove_guest_party_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='second_address',
            field=models.CharField(blank=True, help_text='Apartment Number if needed', max_length=64, null=True, verbose_name='Second Address'),
        ),
    ]
