# Generated by Django 3.1.5 on 2021-01-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_auto_20210117_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='party',
            name='email',
        ),
        migrations.AlterField(
            model_name='party',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Phone (Texting)'), ('mail', 'Postal Mail')], default='mail', max_length=16, verbose_name='Preferred Contact Method'),
        ),
    ]
