# Generated by Django 3.1.6 on 2021-03-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_remove_guest_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='save_the_date_sent',
            field=models.BooleanField(default=False),
        ),
    ]
