# Generated by Django 4.0.4 on 2022-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_party_code_alter_guest_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='code',
            field=models.CharField(default='', editable=False, help_text='Unique code that identifies the party', max_length=4, unique=True, verbose_name='Party Code'),
        ),
    ]
