# Generated by Django 4.0.4 on 2022-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0014_remove_party_is_attending_party_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='meal',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('steak', 'steak'), ('vegetarian', 'Vegetarian Pasta')], max_length=12, null=True),
        ),
    ]
