# Generated by Django 4.0.4 on 2022-05-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0015_guest_meal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'default_related_name': 'guests', 'ordering': ['party', 'id']},
        ),
    ]
