# Generated by Django 4.0.4 on 2022-05-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_alter_guest_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='code',
            field=models.CharField(default='', help_text='Unique code that identifies the party', max_length=4, unique=True, verbose_name='Party Code'),
        ),
    ]
