# Generated by Django 4.0.4 on 2022-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_alter_guest_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('chicken', 'Chicken'), ('steak', 'Steak'), ('vegetarian', 'Vegetarian Pasta'), ('tenders', 'Kids: Chicken Tenders'), ('macnche', 'Kids: Mac n Cheese')], max_length=12, null=True),
        ),
    ]
