# Generated by Django 3.1.5 on 2021-01-10 20:40

import django.core.validators
from django.db import migrations, models
import wedding.public.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('picture', models.ImageField(upload_to=wedding.public.models.gallery_picture_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=wedding.public.models.gallery_thumbnail_path)),
            ],
            options={
                'verbose_name_plural': 'Gallery Items',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('link', models.URLField()),
                ('icon', models.CharField(choices=[('heart-1', 'Ceremony'), ('wine', 'Reception'), ('plane', 'Airport'), ('tree', 'Parks and Greenspace'), ('star', 'Tourist Attraction')], max_length=32)),
                ('details', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, help_text='Use <a href="https://www.latlong.net/convert-address-to-lat-long.html" target="_blank">Visit here</a> to get values', max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, help_text='Use <a href="https://www.latlong.net/convert-address-to-lat-long.html" target="_blank">Visit here</a> to get values', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to=wedding.public.models.registry_thumbnail_path)),
                ('link', models.URLField(help_text='Link to redirect clicks to')),
            ],
            options={
                'verbose_name_plural': 'Registry Organizations',
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Entry Title')),
                ('month', models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], help_text='Abbreviation for the month to show', verbose_name='Month')),
                ('year', models.IntegerField(help_text='Can be between 2013 and 2022', validators=[django.core.validators.MinValueValidator(2013), django.core.validators.MaxValueValidator(2022)])),
                ('details', models.TextField()),
                ('picture', models.ImageField(upload_to=wedding.public.models.entry_picture_path)),
            ],
            options={
                'verbose_name_plural': 'Timeline Entries',
                'ordering': ('year', 'month'),
            },
        ),
    ]
