# Generated by Django 3.1.5 on 2021-01-09 05:33

import django.core.validators
from django.db import migrations, models
import wedding.public.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Entry Title')),
                ('month', models.CharField(help_text='Abbreviation for the month to show', max_length=3, verbose_name='Month Abbreviation')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2022)])),
                ('details', models.TextField()),
                ('picture', models.ImageField(upload_to=wedding.public.models.entry_picture_path)),
            ],
        ),
    ]
