# Generated by Django 3.1.5 on 2021-01-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='month',
            field=models.IntegerField(choices=[(1, 'January')], help_text='Abbreviation for the month to show', verbose_name='Month'),
        ),
    ]
