# Generated by Django 3.1.5 on 2021-01-09 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20210109_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineentry',
            options={'ordering': ('year', 'month')},
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], help_text='Abbreviation for the month to show', verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='year',
            field=models.IntegerField(help_text='Can be between 2013 and 2022', validators=[django.core.validators.MinValueValidator(2013), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
