# Generated by Django 3.1.5 on 2021-01-13 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20210113_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='year',
            field=models.IntegerField(help_text='Can be between 2010 and 2022', validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
