# Generated by Django 3.1.5 on 2021-01-09 17:47

from django.db import migrations, models
import wedding.public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20210109_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('picture', models.ImageField(upload_to=wedding.public.models.gallery_picture_path)),
            ],
        ),
    ]
