# Generated by Django 3.1.5 on 2021-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20210113_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryorganization',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
