# Generated by Django 3.1.5 on 2021-01-09 18:01

from django.db import migrations, models
import wedding.public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=wedding.public.models.gallery_thumbnail_path),
        ),
    ]
