# Generated by Django 3.1.5 on 2021-01-09 18:08

from django.db import migrations
import sorl.thumbnail.fields
import wedding.public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_galleryitem_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(upload_to=wedding.public.models.gallery_picture_path),
        ),
    ]
