# Generated by Django 3.1.5 on 2021-01-09 18:10

from django.db import migrations, models
import wedding.public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20210109_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='picture',
            field=models.ImageField(upload_to=wedding.public.models.gallery_picture_path),
        ),
    ]
