# Generated by Django 3.1.5 on 2021-01-09 18:49

from django.db import migrations, models
import wedding.public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20210109_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to=wedding.public.models.registry_thumbnail_path)),
                ('link', models.URLField(help_text='Link to redirect clicks to')),
            ],
            options={
                'verbose_name_plural': 'Registry Organizations',
            },
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='timelineentry',
            options={'ordering': ('year', 'month'), 'verbose_name_plural': 'Timeline Entries'},
        ),
    ]
